<?php

const SITE_HOSTNAME = "EXAMPLE_HOSTNAME";
const DATA_MOUNT_PATH = "/mnt";
const DEFAULT_API_KEY = "EXAMPLE_DEFAULT_API_KEY";
const MAX_RESULTS = 6;

const IRC_SERVER_HOST = "EXAMPLE_IRC_SERVER_HOST";
const IRC_SERVER_PORT = 6697;
const IRC_SERVER_PASS = "EXAMPLE_IRC_SERVER_PASS"; //Can be left empty
const BOT_NICK = "EXAMPLE_BOT_NICK";
const BOT_USER = "EXAMPLE_BOT_USER";
const BOT_KEYID = "EXAMPLE_BOT_KEYID";
const BOT_PASSWORD = "EXAMPLE_BOT_PASSWORD";
const BOT_USE_SATSUKI = false;
const BOT_RADIO_CHANNEL = "EXAMPLE_RADIO_CHANNEL";
const BOT_NP_CHANNEL = "EXAMPLE_NP_CHANNEL";

const DB_MUSIC_CONNSTRING = "EXAMPLE_PSQL_STRING_MUSIC";
const DB_TORRENTS_CONNSTRING = "EXAMPLE_PSQL_STRING_TORRENTS";

const HOST_NGINX = "nginx:80";
const HOST_API = "api:8011";
const HOST_KAWA = "kawa:4040";
const HOST_KAWA_STREAM = "kawa:8001";
